Chapter 07
# 利用两层列表生成式计算矩阵逐项积
Book_1《编程不难》 | 鸢尾花书：从加减乘除到机器学习 

In [15]:
def hadamard_prod(M1, M2):
    if (len(M1) != len(M2) or 
        len(M1[0]) != len(M2[0])):
        raise ValueError("Matrices must have the same shape")

    result = [[M1[i][j] * M2[i][j] 
               for j in range(len(M1[0]))] 
              for i in range(len(M1))]
    return result

In [16]:
A = [[1, 2],
     [3, 4]]
B = [[2, 3],
     [4, 5]]

In [17]:
# 计算矩阵逐项积
C = hadamard_prod(A, B)
print(C)

[[2, 6], [12, 20]]


In [18]:
import numpy as np
print(np.array(A)*np.array(B))

[[ 2  6]
 [12 20]]


格式：NumPy 去掉了逗号，用空格分隔，更像数学矩阵
对齐：NumPy 会自动对齐数字列，更易读
类型显示：NumPy 会显示数组类型（如 dtype=int64）
省略号：大矩阵时 NumPy 会用 ... 省略中间部分
## 原生
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

## NumPy
[[1 2 3]  
 [4 5 6]  
 [7 8 9]]
